apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policyset-blastwall-test
  namespace: acm-spo-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-spo-test
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: PolicySet
    name: policyset-blastwall-test
