apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - policy-blastwall-spo-profiles.yaml
  - policy-prevent-copy-fail-cve-ds.yaml
  - policy-spo-rawselinuxprofile-crd.yaml
  - policy-spo-selinux-smoke.yaml
  - policyset-blastwall.yaml
  - policyset-spo.yaml
