apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - policy-blastwall-v2-raw-profiles.yaml
  - policy-blastwall-v2-profile-usage.yaml
  - policy-blastwall-v2-runtime-bindings.yaml
  - policy-install-spo-operator.yaml
  - policy-prevent-copy-fail-cve-ds.yaml
  - policy-spo-rawselinuxprofile-crd.yaml
  - policy-spo-selinux-smoke.yaml
  - policyset-blastwall.yaml
  - policyset-spo.yaml
