apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-spo-selinux-smoke-extra
  namespace: acm-spo-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: spo-selinux-smoke-extra-profile
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: security-profiles-operator.x-k8s.io/v1alpha2
                kind: SelinuxProfile
                metadata:
                  name: acm-spo-smoke-extra
                spec:
                  inherit:
                    - kind: System
                      name: container
